---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: yolo
      tier: client
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: yolo
        tier: client
        track: stable
    spec:
      containers:
        - name: hello
          image: "us-central1-docker.pkg.dev/grand-highway-256907/yolo-client/yolo-gke:latest"
          ports:
          - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "1Gi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
    